export const ageList = [
  'child',
  'juvenile',
  'teenage',
  'young adult',
  'fresh-faced',
  'youthful',
  'prime-aged',
  'fully-grown',
  'seasoned',
  'settled',
  'middle-aged',
  'weathered',
  'mature',
  'aging',
  'elderly',
  'venerable',
  'ancient',
  'well-preserved',
  'time-worn',
  'exceptionally old',
];
