export const buildList = [
  'athletic',
  'muscular',
  'slim',
  'stocky',
  'lean',
  'burly',
  'wiry',
  'stout',
  'lanky',
  'robust',
  'willowy',
  'bulky',
  'petite',
  'solid',
  'well-built',
  'thin',
  'heavyset',
  'sinewy',
  'compact',
  'toned',
  'brawny',
  'svelte',
  'sturdy',
  'slight',
  'powerful',
  'lithe',
  'broad',
  'delicate',
  'thickset',
  'fit',
  'meaty',
  'trim',
  'pudgy',
  'strong',
  'dainty',
  'husky',
  'slender',
  'plump',
  'dense',
  'graceful',
  'buff',
  'skinny',
  'rotund',
  'hardy',
  'small-framed',
  'defined',
  'gaunt',
  'round',
  'tough',
  'fine-boned',
  'chiseled',
  'scrawny',
  'stacked',
  'rugged',
  'bird-boned',
  'cut',
  'spindly',
  'full-figured',
  'strapping',
  'slight',
  'ripped',
  'reedy',
  'thick',
  'hefty',
  'ethereal',
  'sculpted',
  'rake-thin',
  'substantial',
  'musclebound',
  'wispy',
  'built',
  'bony',
  'well-rounded',
  'powerfully-built',
  'fragile-looking',
  'broad-shouldered',
  'skeletal',
  'heavy',
  'herculean',
  'waiflike',
  'developed',
  'gangly',
  'portly',
  'vigorous',
  'diminutive',
  'well-muscled',
  'rangy',
  'sturdily-built',
  'robust',
  'tiny',
  'proportioned',
  'long-limbed',
  'solidly-built',
  'substantial',
  'small-boned',
  'physically-fit',
  'stretched-out',
  'thickly-built',
  'imposing',
  'delicately-built',
];

export const heightList = [
  'extremely short',
  'very short',
  'short',
  'below-average',
  'slightly short',
  'average height',
  'typical height',
  'medium height',
  'slightly tall',
  'somewhat tall',
  'above-average',
  'notably tall',
  'quite tall',
  'very tall',
  'exceptionally tall',
  'towering',
  'statuesque',
  'imposing',
  'looming',
  'remarkably tall',
];
