export const eyeColorTraits = [
  'deep brown',
  'ice blue',
  'forest green',
  'storm gray',
  'amber',
  'violet',
  'hazel',
  'pale blue',
  'dark green',
  'golden brown',
  'steel blue',
  'emerald green',
  'copper brown',
  'midnight blue',
  'sea green',
  'silver gray',
  'mismatched',
  'jade green',
  'obsidian black',
  'crystal blue',
  'chocolate brown',
  'sky blue',
  'moss green',
  'slate gray',
  'honey brown',
  'navy blue',
  'olive green',
  'charcoal gray',
  'russet brown',
  'azure blue',
  'pine green',
  'dove gray',
  'mahogany brown',
  'cerulean blue',
  'sage green',
  'pewter gray',
  'sepia brown',
  'cobalt blue',
  'lime green',
  'ash gray',
  'umber brown',
  'turquoise blue',
  'kelly green',
  'smoke gray',
  'tawny brown',
  'indigo blue',
  'fern green',
  'graphite gray',
  'cognac brown',
  'arctic blue',
  'laurel green',
  'stone gray',
  'espresso brown',
  'sapphire blue',
  'mint green',
  'flint gray',
  'cinnamon brown',
  'cornflower blue',
  'basil green',
  'iron gray',
  'mocha brown',
  'periwinkle blue',
  'spring green',
  'nickel gray',
  'caramel brown',
  'aquamarine',
  'hunter green',
  'platinum gray',
  'walnut brown',
  'robin egg blue',
  'moss green',
  'slate blue',
  'taupe brown',
  'teal blue',
  'forest brown',
  'ocean blue',
  'earth brown',
  'sky gray',
  'coffee brown',
  'river blue',
  'grass green',
  'cloud gray',
  'bark brown',
  'lake blue',
  'leaf green',
  'mist gray',
  'root brown',
  'wave blue',
  'meadow green',
  'shadow gray',
  'soil brown',
  'dawn blue',
  'vine green',
  'dusk gray',
  'sand brown',
  'twilight blue',
  'reed green',
  'fog gray',
  'clay brown',
  'night blue',
  'light brown',
  'pale green',
  'light gray',
  'dark brown',
  'bright blue',
  'soft green',
  'cool gray',
  'warm brown',
  'deep blue',
  'rich green',
  'pure gray',
  'golden brown',
  'clear blue',
  'vivid green',
  'stormy gray',
  'amber brown',
  'gentle blue',
  'fresh green',
  'steely gray',
  'earthy brown',
  'crystalline blue',
  'natural green',
  'metallic gray',
  'chocolate black',
  'aqua blue',
];

export const eyeShapeTraits = [
  'almond-shaped',
  'round',
  'upturned',
  'downturned',
  'hooded',
  'wide-set',
  'close-set',
  'deep-set',
  'protruding',
  'sunken',
  'large',
  'small',
  'narrow',
  'broad',
  'slanted',
  'heavy-lidded',
  'drooping',
  'angular',
  'elongated',
  'oval',
  'prominent',
  'recessed',
  'symmetrical',
  'asymmetrical',
  'cat-like',
  'doe-like',
  'hawk-like',
  'fox-like',
  'puppy-like',
  'wolf-like',
  'sleepy',
  'alert',
  'intense',
  'gentle',
  'piercing',
  'squinting',
  'wide',
  'thin',
  'stretched',
  'compressed',
  'bulging',
  'beady',
  'bright',
  'dull',
  'sharp',
  'soft',
  'focused',
  'unfocused',
  'clear',
  'cloudy',
  'gleaming',
  'shadowed',
  'lined',
  'smooth',
  'creased',
  'baggy',
  'puffy',
  'sunken',
  'hollow',
  'full',
  'taut',
  'relaxed',
  'stressed',
  'peaceful',
  'worried',
  'laughing',
  'serious',
  'playful',
  'stern',
  'kind',
  'cruel',
  'warm',
  'cold',
  'distant',
  'inviting',
  'mysterious',
  'open',
  'guarded',
  'expressive',
  'blank',
  'lively',
  'tired',
  'energetic',
  'weary',
  'youthful',
  'aged',
  'wise',
  'innocent',
  'knowing',
  'naive',
  'calculating',
  'honest',
  'shifty',
  'direct',
  'avoiding',
  'focused',
  'wandering',
  'steady',
  'wavering',
  'fixed',
];
