export const featuresList = [
  'a missing front tooth',
  'a crooked nose',
  'a large facial scar',
  'a noticeable birthmark',
  'protruding ears',
  'an eye patch',
  'a burn scar on the neck',
  'a crooked smile',
  'a prominent mole',
  'a hooked nose',
  'thick, bushy eyebrows',
  'a drooping eyelid',
  'a noticeable limp',
  'several missing fingers',
  'a weathered face',
  'rough, calloused hands',
  'a crooked, broken nose',
  'intricate tribal tattoos',
  'traditional sailor tattoos',
  'multiple facial piercings',
  'a face full of freckles',
  'a distinctive birthmark',
  'deep pockmarks across the face',
  'a missing ear',
  'a long knife scar',
  'a noticeable swagger',
  'a pronounced hunch',
  'an unfocused eye',
  'gnarled, twisted fingers',
  'exceptionally long nails',
  'a noticeable gap between the teeth',
  'a prominent gold tooth',
  'a gleaming silver tooth',
  'a single black tooth',
  'reddened, sunburned skin',
  'wind-chapped cheeks',
  'deeply tanned skin',
  'an extremely pale complexion',
  'perpetually rosy cheeks',
  'a ruddy complexion',
  'noticeably yellowed teeth',
  'remarkably straight teeth',
  'an infectious smile',
  'deep cheek dimples',
  'sharp, high cheekbones',
  'a distinctly angular jaw',
  'a prominently strong chin',
  'a notably recessed chin',
  'a pronounced double chin',
  "a protruding Adam's apple",
  'an unusually long neck',
  'a thick, muscular neck',
  'exceptionally broad shoulders',
  'notably narrow shoulders',
  'a permanent stoop',
  'impeccable posture',
  'a distinct slouch',
  'numerous battle scars',
  'ritualistic scarification',
  'a branded symbol',
  'intricately painted nails',
  'permanently stained hands',
  'ink-stained fingertips',
  'perpetually dirty nails',
  'perfectly manicured nails',
  'notably rough hands',
  'unusually soft hands',
  'elegant, graceful hands',
  'deeply wrinkled hands',
  'an abundance of jewelry',
  'a partially missing eyebrow',
  'a scarred eyebrow',
  'completely bare eyebrows',
  'carefully drawn eyebrows',
  'precisely plucked eyebrows',
  'full, thick lips',
  'remarkably thin lips',
  'perpetually chapped lips',
  'brightly painted lips',
  'a visible cleft lip',
  'a distinctive cleft chin',
  'deep facial wrinkles',
  'pronounced laugh lines',
  'noticeable worry lines',
  'deep frown lines',
  "pronounced crow's feet",
  'remarkably smooth skin',
  'noticeable acne scars',
  'thin razor scars',
  'a misshapen ear',
  'visible, prominent veins',
  'tough, leathery skin',
  'unusually smooth skin',
  'noticeably rough skin',
  'a pronounced pot belly',
  'a broad barrel chest',
  'a noticeably sunken chest',
  'an impressively broad chest',
  'an especially narrow chest',
  'visibly knock-kneed legs',
  'distinctly bowed legs',
  'unusually long legs',
  'notably short legs',
  'impressively muscular arms',
  'remarkably thin arms',
  'exceptionally hairy arms',
  'completely hairless arms',
  'unusually long fingers',
  'notably short fingers',
  'thick, stubby fingers',
  'elegant, tapering fingers',
  'twisted, gnarled fingers',
];
