export const hairColorTraits = [
  'raven black',
  'golden blonde',
  'rich auburn',
  'chestnut brown',
  'silver gray',
  'platinum blonde',
  'dark brown',
  'honey blonde',
  'ash gray',
  'russet brown',
  'jet black',
  'sandy blonde',
  'steel gray',
  'chocolate brown',
  'strawberry blonde',
  'salt-and-pepper',
  'pure white',
  'copper red',
  'mahogany brown',
  'flaxen blonde',
  'inky black',
  'wheat blonde',
  'charcoal gray',
  'tawny brown',
  'ginger red',
  'pewter gray',
  'ash blonde',
  'ebony black',
  'caramel brown',
  'bright red',
  'dusty brown',
  'golden brown',
  'mouse brown',
  'dark auburn',
  'light brown',
  'pale blonde',
  'rich brown',
  'dark red',
  'golden red',
  'warm brown',
  'cool brown',
  'honey brown',
  'amber blonde',
  'dirty blonde',
  'butterscotch blonde',
  'espresso brown',
  'onyx black',
  'champagne blonde',
  'burgundy red',
  'chocolate black',
  'slate gray',
  'dove gray',
  'iron gray',
  'smoke gray',
  'stone gray',
  'blue black',
  'wine red',
  'rusty red',
  'cherry red',
  'bronze brown',
  'sepia brown',
  'faded black',
  'ash brown',
  'shadow black',
  'cocoa brown',
  'coal black',
  'brunette',
  'dark blonde',
  'light blonde',
  'medium brown',
  'purple-streaked black',
  'blue-tinted black',
  'green-tinted black',
  'red-tinted brown',
  'gold-streaked brown',
  'silver-streaked black',
  'copper-streaked brown',
  'platinum-streaked blonde',
  'white-streaked gray',
  'red-streaked black',
  'black and white',
  'brown and blonde',
  'red and black',
  'gray and white',
  'blonde and brown',
  'deep purple',
  'midnight blue',
  'forest green',
  'blood red',
  'royal blue',
  'emerald green',
  'deep crimson',
  'electric blue',
  'jade green',
  'ruby red',
  'sapphire blue',
  'amethyst purple',
  'turquoise blue',
  'lime green',
  'magenta pink',
  'lavender purple',
  'teal blue',
  'neon green',
  'hot pink',
  'violet purple',
];

export const hairStyleTraits = [
  'single braid',
  'ponytail',
  'neat bun',
  'set of pigtails',
  'mohawk style',
  'crew cut',
  'bob cut',
  'pixie cut',
  'topknot style',
  'undercut style',
  'mullet style',
  'fade cut',
  'natural afro',
  'set of cornrows',
  'set of dreadlocks',
  'set of twists',
  'set of locks',
  'wavy style',
  'curly style',
  'set of ringlets',
  'formal updo',
  'chignon style',
  'French twist',
  'crown braid style',
  'fishtail braid',
  'side braid',
  'dutch braid',
  'set of box braids',
  'set of micro braids',
  'rope braid',
  'waterfall braid',
  'milkmaid braid style',
  'set of space buns',
  'low bun',
  'high bun',
  'messy bun',
  'sock bun',
  'twist out style',
  'set of bantu knots',
  'set of finger coils',
  'buzz cut',
  'bowl cut',
  'wedge cut',
  'pageboy cut',
  'shag cut',
  'layered cut',
  'feathered style',
  'asymmetric cut',
  'side swept style',
  'slicked back style',
  'pompadour style',
  'quiff style',
  'faux hawk style',
  'hi-top fade cut',
  'temple fade cut',
  'taper fade cut',
  'disconnected undercut',
  'side part style',
  'middle part style',
  'zigzag part style',
  'fringe cut',
  'side fringe style',
  'curtain fringe style',
  'wispy fringe style',
  'blunt fringe cut',
  'spiked style',
  'liberty spike style',
  'death hawk style',
  'rat tail style',
  'ducktail style',
  'flattop cut',
  'ivy league cut',
  'caesar cut',
  'princeton cut',
  'regulation cut',
  'high and tight cut',
  'brush cut',
  'induction cut',
  'burr cut',
  'butch cut',
  'fade cut',
  'tapered cut',
  'cropped cut',
  'textured crop cut',
  'French crop cut',
  'comb over style',
  'side sweep style',
  'slicked style',
  'natural style',
  'protective style',
  'wash and go style',
  'blowout style',
  'pressed style',
  'relaxed style',
  'texturized style',
  'coiled style',
  'kinky style',
  'spiral style',
  'wavy pattern',
  'roller set style',
  'set of pin curls',
  'set of barrel curls',
  'set of spiral curls',
  'beach wave style',
  'finger wave pattern',
  'marcel wave pattern',
  'crimped style',
  'teased style',
  'bouffant style',
  'beehive style',
];
