export const mannerismTraits = [
  'are constantly fidgeting',
  'sometimes talk to themselves',
  'laugh after speaking',
  'avoid eye contact',
  'use big words incorrectly',
  'bite their fingernails',
  'are always scratching their neck',
  'touch others while speaking',
  'speak in metaphors',
  'are constantly stretching',
  'often crack their knuckles',
  'continually adjust their clothing',
  'play with their hair',
  'pace while thinking',
  'speak in the third person',
  'hum while working',
  'count on their fingers',
  'collect small objects',
  'draw in the air',
  'quote ancient texts',
  'whistle tunes',
  'speak to animals',
  'use formal titles',
  'tell bad jokes',
  'give nicknames',
  'speak in riddles',
  'make animal sounds',
  "repeat others' last words when conversing",
  'use hand signals',
  'wink frequently',
  'give out lucky charms',
  'salute everyone',
  'are always slightly bowing',
  'speak in whispers',
  'stand too close',
  'ask rhetorical questions',
  'tell long stories',
  'quote prophecies',
  'make predictions',
  'offer blessings',
  'mutter curses',
  'spit for luck',
  'often touch their lucky charm',
  'avoid certain words',
  'use colorful curse words',
  'snap their fingers',
  'tap their foot',
  'drum their fingers',
  'rock back and forth',
  'polish objects',
  'are always organizing their items',
  'collect trinkets',
  'name their possessions',
  'make lists',
  'draw patterns',
  'follow rituals',
  'are always checking the time',
  'count their steps',
  'measure things',
  'test the wind',
  'taste food extensively',
  'sniff the air',
  'watch shadows attentively',
  'track the sun',
  'predict the weather',
  'interpret signs',
  'read palms',
  'examine clouds',
  'study faces',
  'sketch constantly',
  'juggle items',
  'perform tricks',
  'constantly try to show off',
  'challenge others',
  'tell tall tales',
  'make bets',
  'play games',
  'solve puzzles',
  'create riddles',
  'invent new words',
  'mimic others',
  'change their accent',
  'use slang',
  'create metaphors',
  'tell secrets',
  'share rumors',
  'spread gossip',
  'keep records',
  'take notes',
  'draw maps',
  'name stars',
  'trace symbols',
  'create songs',
  'invent stories',
  'write poems',
  'carve markings',
  'leave signs',
  'make monuments',
  'build shrines',
  'create art',
  'perform rituals',
  'teach lessons',
  'give advice',
  'share wisdom',
  'tell fortunes',
  'interpret dreams',
  'read omens',
  'sense danger',
  'feel some kind of "energy"',
  'hear spirits',
];
