export const mannerismsList = [
  'constantly fidgets',
  'talks to self',
  'laughs after speaking',
  'avoids eye contact',
  'uses big words incorrectly',
  'bites fingernails',
  'scratches neck',
  'touches others while speaking',
  'speaks in metaphors',
  'constantly stretches',
  'cracks knuckles',
  'adjusts clothing',
  'plays with hair',
  'paces while thinking',
  'speaks in third person',
  'hums while working',
  'counts on fingers',
  'collects small objects',
  'draws in the air',
  'quotes ancient texts',
  'whistles tunes',
  'speaks to animals',
  'uses formal titles',
  'tells bad jokes',
  'gives nicknames',
  'speaks in riddles',
  'makes animal sounds',
  'repeats last words',
  'uses hand signals',
  'winks frequently',
  'gives lucky charms',
  'salutes everyone',
  'bows slightly',
  'speaks in whispers',
  'stands too close',
  'asks rhetorical questions',
  'tells long stories',
  'quotes prophecies',
  'makes predictions',
  'offers blessings',
  'mutters curses',
  'spits for luck',
  'touches lucky charm',
  'avoids certain words',
  'uses colorful curse words',
  'snaps fingers',
  'taps foot',
  'drums fingers',
  'rocks back and forth',
  'polishes objects',
  'organizes items',
  'collects trinkets',
  'names possessions',
  'makes lists',
  'draws patterns',
  'follows rituals',
  'checks time',
  'counts steps',
  'measures things',
  'tests wind',
  'tastes food extensively',
  'sniffs air',
  'watches shadows',
  'tracks sun',
  'predicts weather',
  'interprets signs',
  'reads palms',
  'examines clouds',
  'studies faces',
  'sketches constantly',
  'juggles items',
  'performs tricks',
  'shows off',
  'challenges others',
  'tells tall tales',
  'makes bets',
  'plays games',
  'solves puzzles',
  'creates riddles',
  'invents words',
  'mimics others',
  'changes accent',
  'uses slang',
  'creates metaphors',
  'tells secrets',
  'shares rumors',
  'spreads gossip',
  'keeps records',
  'takes notes',
  'draws maps',
  'names stars',
  'traces symbols',
  'creates songs',
  'invents stories',
  'writes poems',
  'carves markings',
  'leaves signs',
  'makes monuments',
  'builds shrines',
  'creates art',
  'performs rituals',
  'teaches lessons',
  'gives advice',
  'shares wisdom',
  'tells fortunes',
  'interprets dreams',
  'reads omens',
  'senses danger',
  'feels energy',
  'hears spirits',
];
