export const plotHookTraits = [
  'need help moving heavy furniture',
  'are searching for a lost pet',
  'want to deliver a message to someone',
  'need an escort to a nearby town',
  'are looking for rare ingredients',
  'want help organizing a local festival',
  'need someone to decipher a letter',
  'are seeking witnesses to an incident',
  'want to learn a new skill',
  'need help with inventory',
  'are collecting signatures for a petition',
  'want to find a specific book',
  'need help repairing a home',
  'are looking for a missing sibling',
  'want to trade goods',
  'need a guard for a shop',
  'are seeking an apprentice',
  'want to map an area',
  'need help gathering supplies',
  'are looking for temporary workers',
  'want to track down a debtor',
  'need help with farming',
  'are searching for building materials',
  'want to learn about local customs',
  'need translation assistance',
  'are planning a surprise party',
  'want to authenticate an item',
  'need help with bookkeeping',
  'are seeking travel companions',
  'want to commission artwork',
  'need someone to test a product',
  'are looking for investment opportunities',
  'want to investigate strange noises',
  'need help setting up shop',
  'are seeking legal advice',
  'want to locate a rare merchant',
  'need help with heavy lifting',
  'are looking for storytellers',
  'want to arrange a meeting',
  'need directions to somewhere',
  'are seeking relationship advice',
  'want to resolve a dispute',
  'need help organizing records',
  'are looking for lost property',
  'want to discover family history',
  'need assistance with cooking',
  'are seeking musical instruction',
  'want to deliver packages',
  'need help cleaning up',
  'are looking for temporary lodging',
  'want to exchange information',
  'need someone to watch a store',
  'are seeking building advice',
  'want to learn local history',
  'need help with gardening',
  'are looking for rare collectibles',
  'want to plan an event',
  'need help moving livestock',
  'are seeking fashion advice',
  'want to find old records',
  'need assistance with crafting',
  'are looking for teaching work',
  'want to establish trade routes',
  'need help with decorating',
  'are seeking performance space',
  'want to document local legends',
  'need help with research',
  'are looking for specific tools',
  'want to arrange transportation',
  'need courier services',
  'are seeking mining locations',
  'want to explore local ruins',
  'need help with fishing',
  'are looking for hunting spots',
  'want to gather wild herbs',
  'need assistance with brewing',
  'are seeking carpentry help',
  'want to organize storage',
  'need help with animals',
  'are looking for construction workers',
  'want to learn local songs',
  'need help with navigation',
  'are seeking farming advice',
  'want to find rare seeds',
  'need assistance with sewing',
  'are looking for entertainment',
  'want to arrange meetings',
  'need help with paperwork',
  'are seeking expert opinions',
  'want to verify rumors',
  'need help with maintenance',
  'are looking for specific materials',
  'want to learn trade skills',
  'need assistance with painting',
  'are seeking music lessons',
  'want to catalog items',
  'need help with inventory',
  'are looking for specific foods',
  'want to practice conversation',
  'need translation help',
];
