export const plotHookTraits = [
  'needs help moving heavy furniture',
  'is searching for a lost pet',
  'wants to deliver a message to someone',
  'needs an escort to a nearby town',
  'is looking for rare ingredients',
  'wants help organizing a local festival',
  'needs someone to decipher a letter',
  'is seeking witnesses to an incident',
  'wants to learn a new skill',
  'needs help with inventory',
  'is collecting signatures for a petition',
  'wants to find a specific book',
  'needs help repairing a home',
  'is looking for a missing sibling',
  'wants to trade goods',
  'needs a guard for a shop',
  'is seeking an apprentice',
  'wants to map an area',
  'needs help gathering supplies',
  'is looking for temporary workers',
  'wants to track down a debtor',
  'needs help with farming',
  'is searching for building materials',
  'wants to learn about local customs',
  'needs translation assistance',
  'is planning a surprise party',
  'wants to authenticate an item',
  'needs help with bookkeeping',
  'is seeking travel companions',
  'wants to commission artwork',
  'needs someone to test a product',
  'is looking for investment opportunities',
  'wants to investigate strange noises',
  'needs help setting up shop',
  'is seeking legal advice',
  'wants to locate a rare merchant',
  'needs help with heavy lifting',
  'is looking for storytellers',
  'wants to arrange a meeting',
  'needs directions to somewhere',
  'is seeking relationship advice',
  'wants to resolve a dispute',
  'needs help organizing records',
  'is looking for lost property',
  'wants to discover family history',
  'needs assistance with cooking',
  'is seeking musical instruction',
  'wants to deliver packages',
  'needs help cleaning up',
  'is looking for temporary lodging',
  'wants to exchange information',
  'needs someone to watch a store',
  'is seeking building advice',
  'wants to learn local history',
  'needs help with gardening',
  'is looking for rare collectibles',
  'wants to plan an event',
  'needs help moving livestock',
  'is seeking fashion advice',
  'wants to find old records',
  'needs assistance with crafting',
  'is looking for teaching work',
  'wants to establish trade routes',
  'needs help with decorating',
  'is seeking performance space',
  'wants to document local legends',
  'needs help with research',
  'is looking for specific tools',
  'wants to arrange transportation',
  'needs courier services',
  'is seeking mining locations',
  'wants to explore local ruins',
  'needs help with fishing',
  'is looking for hunting spots',
  'wants to gather wild herbs',
  'needs assistance with brewing',
  'is seeking carpentry help',
  'wants to organize storage',
  'needs help with animals',
  'is looking for construction workers',
  'wants to learn local songs',
  'needs help with navigation',
  'is seeking farming advice',
  'wants to find rare seeds',
  'needs assistance with sewing',
  'is looking for entertainment',
  'wants to arrange meetings',
  'needs help with paperwork',
  'is seeking expert opinions',
  'wants to verify rumors',
  'needs help with maintenance',
  'is looking for specific materials',
  'wants to learn trade skills',
  'needs assistance with painting',
  'is seeking music lessons',
  'wants to catalog items',
  'needs help with inventory',
  'is looking for specific foods',
  'wants to practice conversation',
  'needs translation help',
];
